project:
  type: website
  output-dir: ../docs
website:
  title: "England and Wales Census Maps 2021"
  google-analytics: "UA-6248530-1"
  navbar:
      background: light
      search: true
      left:
       - text: "NE"
         file: posts/E12000001.qmd
       - text: "NW"
         file: posts/E12000002.qmd
       - text: "Yorkshire and The Humber"
         file: posts/E12000003.qmd
       - text: "EM"
         file: posts/E12000004.qmd
       - text: "WM"
         file: posts/E12000005.qmd
       - text: "EE"
         file: posts/E12000006.qmd
       - text: "London"
         file: posts/E12000007.qmd
       - text: "SE"
         file: posts/E12000008.qmd
       - text: "SW"
         file: posts/E12000009.qmd
       - text: "Wales"
         file: posts/W92000004.qmd
format:
  html:
    theme: litera
    css: styles.css
